# Generated by Django 3.2.11 on 2023-12-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeeducation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeeresume',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
        migrations.DeleteModel(
            name='EmployeeEducation',
        ),
        migrations.DeleteModel(
            name='EmployeeExperience',
        ),
        migrations.DeleteModel(
            name='EmployeeResume',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
